/**
 * Vercel Routing Middleware (proxy) for anuran.dev.
 * - Markdown negotiation per acceptmarkdown.com: Accept: text/markdown -> .md twin + Vary: Accept
 * - Preserves all existing visuals/interactions (headless rewrites only).
 */
export default function proxy(request) {
  const url = new URL(request.url);
  const pathname = url.pathname;
  const accept = request.headers.get("accept") || "";

  if (!accept.includes("text/markdown")) {
    return fetch(request);
  }

  // Skip non-content paths: APIs, internals, assets, files with extensions.
  if (
    pathname.startsWith("/api/") ||
    pathname.startsWith("/_astro/") ||
    pathname.startsWith("/pagefind/") ||
    pathname.startsWith("/images/") ||
    pathname.startsWith("/documents/") ||
    pathname === "/favicon.png" ||
    pathname === "/favicon.svg" ||
    pathname === "/robots.txt" ||
    pathname === "/rss.xml" ||
    pathname === "/sitemap-index.xml" ||
    pathname === "/sitemap-0.xml" ||
    pathname === "/openapi.json" ||
    pathname === "/llms.txt" ||
    pathname === "/llms-full.txt" ||
    /\.[a-zA-Z0-9]+$/.test(pathname)
  ) {
    return fetch(request);
  }

  // Map content path -> markdown twin generated by astro-llms-md.
  // Homepage / -> /.md (astro-llms-md emits dist/.md for index).
  let mdPath;
  if (pathname === "/") {
    mdPath = "/.md";
  } else if (pathname.endsWith("/")) {
    mdPath = `${pathname.slice(0, -1)}.md`;
  } else {
    mdPath = `${pathname}.md`;
  }

  const mdUrl = new URL(mdPath, url);
  // Rewrite to static .md (served as text/markdown). Vary header is set via vercel.json.
  return fetch(new Request(mdUrl.toString(), request));
}

export const config = {
  matcher: "/:path*",
};
